In [1]:
# custom function imports
from utils import make_nanoribbon, generate_structure
# from utils.structure import _reorder_atoms
# base module imports
import sisl
import numpy as np

# plot imports
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from ase.visualize import view

# interactive plot imports
from ipywidgets import interact
import ipywidgets as widgets

In [2]:
def terminal(width, length, depth) -> list[float]:
    """From the width and length return the atom indices highligting the terminal atoms of depth `d`"""
    atom_idx = []
    for i in range(1, width+1):
        for d in range(depth):
            atom_idx.append(2*i*length - (1+d))
    return atom_idx

WIDTH = 10
LENGTH = 15
DEPTH = 4
AXES = "xy"

terminal_atom_idx = terminal(WIDTH, LENGTH, DEPTH)
full_ribbon = make_nanoribbon(width=WIDTH, length=LENGTH)
full_ribbon.plot(axes=AXES, atoms_style={"atoms": terminal_atom_idx, "color": "red"})

In [3]:
device = make_nanoribbon(width=WIDTH, length=LENGTH-2*DEPTH)
lead = make_nanoribbon(width=WIDTH, length=DEPTH)


r = (0.1, 1.5)
t = (0.0, -2.7)

H_device = sisl.Hamiltonian(device)
H_lead = sisl.Hamiltonian(lead)


H_device.construct([r, t])
H_lead.construct([r,t])

# for H in [H_device, H_lead]:
#     H.construct([r, t])


In [139]:
from sisl.physics import RecursiveSI, SemiInfinite, SelfEnergy
import time
E = 0
directions = ["+A", "-A", "+B", "-B", "+C", "-C"]
# pos = directions[::2]

# def padstring(string, N=1):
#     return " "*N + string + " "*N
# def complex_format(x, **kwargs):
#     digits = kwargs.get("digits", 2)
#     pad = kwargs.get("pad", 6)
#     real_part = x.real
#     imag_sign = "+" if np.sign(x.imag) >= 0 else "-"
#     imag_part = np.abs(x.imag)
#     if np.isclose(real_part, 0) and np.isclose(imag_part, 0): # both zero
#         return padstring("0", N=pad)
#     elif np.isclose(real_part, 0) and (not np.isclose(imag_part, 0)): # only imaginary
#         return padstring(f"{imag_sign}i{imag_part:.{digits}f}", N=pad)
#     elif (not np.isclose(real_part, 0)) and np.isclose(imag_part, 0): # only real
#         return padstring(f"{real_part:.{digits}f}", N=pad)
#     elif (not np.isclose(real_part, 0)) and (not np.isclose(imag_part, 0 )): # both real and imag part non-zero
#         sign = "+" if imag_sign > 0 else "-"
#         outstr = f"{real_part:.{digits}f}" + f"{sign}" + f"i{imag_part:.{digits}f}"
#         return padstring(outstr, N=pad)

formatter = {
    "complex_kind": lambda x: f"{np.round(x, 2)}",
    "int_kind": lambda x: str(x)
             }

with np.printoptions(formatter=formatter, edgeitems=6, linewidth=150, floatmode="maxprec_equal"):
        
    for d in directions[:2]:
        print(f"### Direction : {d}")
        leadSE = RecursiveSI(spgeom=H_lead, infinite=d)
        _SE = leadSE.self_energy(E=E)
        print(_SE)
        print(_SE.sum(), end="\n\n")
        
    


    

### Direction : +A
[[(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 ...
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j) (-0-0j)

In [ ]:
E = 0
K = (0,0,0)
leadSE = RecursiveSI(spgeom=H_device, infinite="-A") # +/- specify whether L or R self-energy when calling `self_energy()` method
SE = leadSE.self_energy(E=E, k=K)
L, R = leadSE.self_energy_lr(E=E, k=K)
L.shape, SE.shape, R.shape


((140, 140), (140, 140), (140, 140))

In [ ]:
H_device.(format="array")

array([[ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -2.7, ...,  0. ,  0. ,  0. ],
       [ 0. , -2.7,  0. , ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , -2.7],
       [ 0. ,  0. ,  0. , ...,  0. , -2.7,  0. ]], shape=(140, 140))

In [ ]:
with np.printoptions(formatter=formatter, edgeitems=3, linewidth=150, floatmode="maxprec_equal"):
    for mat in [L, SE, R]:
        print(mat)
        print(np.argwhere(mat !=0).T)
        print()

[[(-0-30661.64j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 ...
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]]
[[0 0 0 0 0 28 28 28 28 28 56 56 56 56 56 84 84 84 84 84 112 112 112 112 112]
 [0 28 56 84 112 0 28 56 84 112 0 28 56 84 112 0 28 56 84 112 0 28 56 84 112]]

[[(-0-30661.64j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 ...
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]
 [(-0-0j) (-0-0j) (-0-0j) ... (-0-0j) (-0-0j) (-0-0j)]]
[[0 0 0 0 0 28 28 28 28 28 56 56 56 56 56 84 84 84 84 84 112 112 112 112 112]
 [0 28 56 84 112 0 28 56 84 112 0 28 56 84 112 0 28 56 84 112 0 28 56 84 112]]

In [208]:
def update_ham(self, ia, idxs, idxs_xyz):
    pass


In [5]:
view(ribbon.to.ase())

NameError: name 'ribbon' is not defined