In [1]:
from utils import make_nanoribbon, hamiltonian
import numpy as np
import matplotlib.pyplot as plt
from ase.visualize import view
import sisl
from sisl.physics import RecursiveSI
import pandas as pd


In [2]:
WIDTH = 6
LENGTH = 3

In [3]:
nanoribbon = make_nanoribbon(WIDTH, LENGTH - 1)
view(nanoribbon.to.ase())
nanoribbon.plot(axes="xy")

In [26]:
PBC_ham = hamiltonian(nanoribbon)
Ham = PBC_ham.copy()
Ham.set_nsc([1,1,1])
SE = RecursiveSI(PBC_ham, infinite="+A") # use PBC for self energies
print(PBC_ham.nsc)
print(SE.nsc)
print(Ham.nsc)

[3 1 1]
[1 1 1]
[1 1 1]


In [27]:

L, R = SE.self_energy_lr(E=0)

def pretty_print_columns(A, decimals=2, zero_repr="0"):
    """
    Print a 2D NumPy array with per-column alignment.
    Handles complex numbers, negatives, and zeros gracefully.
    """
    A = np.asarray(A)
    if A.ndim != 2:
        raise ValueError("Input must be a 2D array")

    rows, cols = A.shape
    is_complex = np.iscomplexobj(A)

    # Build a string matrix (formatted values)
    str_matrix = np.empty(A.shape, dtype=object)
    for i in range(rows):
        for j in range(cols):
            val = A[i, j]
            if val == 0:
                s = zero_repr
            elif is_complex:
                s = f"{val.real:.{decimals}f}{val.imag:+.{decimals}f}j"
            else:
                s = f"{val:.{decimals}f}"
            str_matrix[i, j] = s

    # Compute per-column widths
    col_widths = [max(len(str_matrix[i, j]) for i in range(rows)) for j in range(cols)]

    # Print rows with proper per-column alignment
    for i in range(rows):
        row_str = " ".join(str_matrix[i, j].rjust(col_widths[j]) for j in range(cols))
        print(row_str)

        
print("H")
pretty_print_columns(Ham.Hk(format="array"), decimals=2)

H
    0     0     0 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0 -2.70 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0 -2.70 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
-2.70 -2.70     0     0     0     0 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0 -2.70 -2.70     0     0     0     0 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0 -2.70     0     0     0     0     0 -2.70     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0 -2.70     0     0     0     0     0 -2.70 -2.70     0     0     0     0     0     0     0     0     0     0     0   

In [28]:
print("L")
pretty_print_columns(L, decimals=2)

L
0.00-31752.30j 0.00+25463.36j 0.00-14131.10j 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
0.00+25463.36j 0.00-20420.03j 0.00+11332.26j 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
0.00-14131.10j 0.00+11332.26j  0.00-6288.93j 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0          0          0          0
             0              0              0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0      

In [50]:
print("R")
pretty_print_columns(R, decimals=1)

R
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0             0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0             0             0     

In [ ]:
Nk = 15
E_list = np.arange(-1, 1, 0.1)
eta = 1e-5

T_k_sum = np.zeros([len(E_list), Nk], dtype=float) # store T(E,k)
kpts = sisl.MonkhorstPack(Ham, [Nk, 1, 1]).k

for ik, kvec in enumerate(kpts):
    print(ik)
    # get k-dependent H and S as arrays
    Hk = Ham.Hk(k=kvec, format="array")
    Sk = Ham.Sk(k=kvec, format="array")
    
    for ie, en in enumerate(E_list):
        print(en)
        En = en + 1j*eta
        # compute surface self-energies for this k:
        SL, SR = SE.self_energy_lr(E=En, k=kvec)
        
        # compute gammas 
        GammaL
        

_IncompleteInputError: incomplete input (2807743708.py, line 13)